### ISSUE TITLE
"refinePatchBFGS failed!"

### ISSUE THREAD

**Issue by hlpan** [pmoulon/CMVS-PMVS#12]
I got this message when I use the new version(the one with NLopt) of this program.
And the dense pointset is of a little error. I use the Kermit (11 picture) dataset.
![image](https://cloud.githubusercontent.com/assets/2967059/8430719/18e1305a-1f66-11e5-8a57-f17a5ea2c0c5.png)

Some output is here:

done
adding seeds
refinePatchBFGS failed!
refinePatchBFGS failed!
refinePatchBFGS failed!
refinePatchBFGS failed!
(12,1413)(9,1296)refinePatchBFGS failed!
(0,423)refinePatchBFGS failed!

**Comment by pmoulon** [comment]
Hi,
the "refinePatchBFGS failed!" message is only a warning.

The points that you have depicted with the red circle can be caused due to a patch mismatch.

Perhaps @rhiestan will have more explanation to provide.

**Comment by rhiestan** [comment]
You can ignore the message "refinePatchBFGS failed!". This means that the non-linear optimizer was not able to find a solution. With previous versions, it also happened, but silently.

**Comment by lglgaigogo** [comment]
@rhiestan @pmoulon I I'm grateful that you paid attentions on my issue. You gays have done a great work .Thank you very much.

**Comment by rhiestan** [comment]
Thanks! But I hope you meant "guys" instead of "gays" :-)

**Comment by rhiestan** [comment]
If you encounter many of those errors in the generated point clouds, you can try to increase the parameters for threshold (to 0.8 for example) and/or minImageNum  (to 4 or 5). You will find both of them in the pmvs_options.txt file.
See also http://www.di.ens.fr/pmvs/documentation.html
In case you use cmvs and genOption, they are command line options for genOption. See here:
http://www.di.ens.fr/cmvs/documentation.html

**Comment by lglgaigogo** [comment]
@rhiestan Thank you for your  suggestion on my problem. I have set the minImageNum to 5, and the problem seemed disappear, but the point size reduced in the same time.  So maybe it really needs me to do some trade-off between the quality and the quantity. Than you for you help. And this is real a great work. ------Hailong Pan
