### ISSUE TITLE
Pre-built Windows 64-bit version... not!

### ISSUE THREAD

**Issue by ManlyStump** [pmoulon/CMVS-PMVS#13]
When I download and run cmvs.exe, genOption.exe or pmvs2.exe from the 64-bit folder, I get an error that they're incompatible with 64-bit Windows! I have got 2010 Redistributable installed, so it's not an error with that.

**Comment by pmoulon** [comment]
Feel free to build your own version if it does not work on your machine.
Follow the instructions https://github.com/pmoulon/CMVS-PMVS/blob/master/Readme.txt#L18

**Comment by rhiestan** [comment]
I just downloaded the binaries again, and they work fine on a 64-bit Windows. What exactly is your error message?
Please try again downloading by using the "Download ZIP" button at the highest directory level, or with git clone.
