### ISSUE TITLE
About PLY, PSET, PATCH

### ISSUE THREAD

**Issue by DirtyHarryLYL** [pmoulon/CMVS-PMVS#14]
Hi,
thank you for the excellent work.
I have met a problem about the results of PMVS2:
there is only S.ply under the results folder, but no  S.patch and S.pset.
I know that in the documentation: make PLY, PSET, PATCH export faster and optional
So please tell me how can I opt the results or it's a running error, and how to fix it.
Thank you very much~

**Comment by pmoulon** [comment]
Hi @DirtyHarryLYL 
As you see here you have just to ask PATCH or PSET to be produced.
https://github.com/pmoulon/CMVS-PMVS/blob/a75153a24155a3260fc6e0a2a542c42b533fb891/program/main/pmvs2.cc#L28

So you have just to add PATCH and/or PSET to your command line ;-)

**Comment by DirtyHarryLYL** [comment]
Thanks~
