### ISSUE TITLE
how to generate surface mesh with color?

### ISSUE THREAD

**Issue by LingyuMa** [pmoulon/CMVS-PMVS#17]
I have managed to output *.pset and *.patch along with *.ply. Then I use *.pset as input to a surface reconstruction software (Screened Poisson Surface Reconstruction) to generate the mesh surface. However, since *.pset does not include any color information, I cannot generate colored mesh. Is there a way to generate colored mesh? or Any recommended software for generating colored mesh using the output of PMVS2?

**Comment by pmoulon** [comment]
You can transfer the color from the point cloud.
See https://www.youtube.com/watch?v=sKKmJdsk7Tg

I would recommend you to use OpenMVS, if your final target is a mesh with texture.
