### ISSUE TITLE
No binaries installed with "make install" on Linux

### ISSUE THREAD

**Issue by eboudrand** [pmoulon/CMVS-PMVS#22]
When I run "make install" (with administrator rights) after compiling source files, I see no binaries copied for example in `/usr/local/bin/`. Only some files for nlopt are installed.
Install output is : 
```
$ sudo make install
[  2%] Built target cmvs_lib
[  6%] Built target image_lib
[  8%] Built target numeric_lib
[ 18%] Built target pmvs_lib
[ 21%] Built target tinycthread
[ 53%] Built target nlopt
[ 55%] Built target pmvs2
[ 57%] Built target genOption
[ 99%] Built target graclus_lib
[100%] Built target cmvs
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/include/nlopt.h
-- Installing: /usr/local/include/nlopt.hpp
-- Installing: /usr/local/include/nlopt.f
-- Installing: /usr/local/lib/libnlopt.a
```

**Comment by pmoulon** [comment]
Since there is no install rules for the CMVS/PMVS binary this is normal.
see => https://github.com/pmoulon/CMVS-PMVS/blob/master/program/main/CMakeLists.txt

Feel free to do a PR that can install the binary

**Comment by eboudrand** [comment]
What means "PR" ?

**Comment by jpwhitney** [comment]
I think it means that you could do a [pull request](https://help.github.com/articles/creating-a-pull-request/) for a [merge](https://help.github.com/articles/merging-a-pull-request/) after you define some [install rules](https://cmake.org/cmake/help/v3.0/command/install.html) in [https://github.com/pmoulon/CMVS-PMVS/blob/master/program/main/CMakeLists.txt](https://github.com/pmoulon/CMVS-PMVS/blob/master/program/main/CMakeLists.txt).

I found some install rules [here](https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt) that you could probably use as a model for your PR.

It doesn't look too difficult, but I don't really know much about it.  If you don't end up doing it I could give it a shot and see how it goes.  It seems like an interesting way to learn how it works, but I don't want to take that opportunity away from you if you really would like to do it.

Do you want to try? ;-)

**Comment by eboudrand** [comment]
I will try :)

**Comment by pmoulon** [comment]
@jpwhitney Is right you must add a set of rules like the following
```
INSTALL(TARGETS target_name DESTINATION bin/)
```
where target_name is the binary name.
