### ISSUE TITLE
Crash in PMVS2

### ISSUE THREAD

**Issue by yetanotherguest** [pmoulon/CMVS-PMVS#24]
Hello, I am using PMVS2 x64 since 2011 under Win 7 with bundler.  Usually, with the 1600 x 1200 pixels limitation of images, I never had any problems. However, recently, I tried to use larger images and then generally (not always) I get PMVS2 to crash at the level of adding seeds. Even with the classical 5 "Town Hall" images I get a crash at this same place. Please find attached a screen of the VS2010 debugger showing the corresponding "Call Stack".  Any clue or recommendation of what I should verify or look for to fix this problem. Thanks in advance. Regards.

![debug-crash-pmvs2](https://cloud.githubusercontent.com/assets/28107484/25580755/b61e36a0-2e83-11e7-81a2-3bcc46a14ac7.png)

**Comment by pmoulon** [comment]
Seems like it access to a position in a array that is out of bounds.
Do you have the same behavior is you use the `level` parameter to a higher value?

**Comment by yetanotherguest** [comment]
Thanks for responding that quickly. Yes, definitely, there is something out of range. Increasing "level" to a higher value does not change the behavior. Sometimes it crashes after adding one seed, sometimes after adding three seeds. on the classic "TownHall" images. However, it never happened when images are limited to 1600x1200, eventhough I was able to generate in some case up to 1 million points with 100 or more images ...
