### ISSUE TITLE
Linux library error

### ISSUE THREAD

**Issue by Tutul-** [pmoulon/CMVS-PMVS#25]
The linux binary are strange.
- cmvs and pmvs2 search for library like liblapack.so.3gf or libblas.so.3gf (possible typo with gf ?)
- cmvs is 32-bit but pmvs2 is 64-bit

**Comment by pmoulon** [comment]
Feel free to help to enhance the project with some cmake find_package.

Regarding the x86/x64 thing you encountered I have no idea about the issue since I don't think there is a particular forced configuration in the cmake files.

**Comment by pmoulon** [comment]
Closing due to lack of feedback.
