### ISSUE TITLE
CMVS runs out of memory

### ISSUE THREAD

**Issue by MaXL130** [pmoulon/CMVS-PMVS#26]
Hello, I am using the 32 bit version of CMVS. As far as I understood, CMVS was made to generate clusters, so that pmvs has no memory issues. 
I tried running CMVS on my dataset, and CMVS also crashes because it allocates more than 2GB of memory on windows.
Is this an issue, that is solveable, or am I using CMVS wrong? I called it with the following parameters:

```cmvs "path/to/bundler/file/" 20 8 ``` 

I noticed that CMVS tries to read all 50 images anyways, but after image number 27 the memory is full. I am working on an eight-core maschine, so the "8" parameter should be set correctly.

**Comment by pmoulon** [comment]
Can you try the 64 bit version?
