### ISSUE TITLE
CMVS memory error

### ISSUE THREAD

**Issue by ManishSahu53** [pmoulon/CMVS-PMVS#28]
I have i7-7700K, 16GB Ram, 6GB 1060GTX.
./cmvs output 100 
Trying to run cmvs command to make cluster but no matter how many number of images I choose it always goes out of memory. Even I have tried putting 1 images then also it goes out of memory. Can you help?
I have processed in openMVG with 471 images(24MP each) geotagged.

**Comment by pmoulon** [comment]
Did you look where the crash is happening?

If I remember well the code is loading the image in memory and so it can be a problem with large project.

I would advise you to use https://github.com/openMVG/openMVG/blob/master/src/software/SfM/clustering/main_ComputeClusters.cpp and I think you already used it.

**Comment by ManishSahu53** [comment]
Yes it get stuck in loading the images. I have 471 images.
I have used openMVG for clustering also. The problem I am facing with that option is of merging after point cloud generation. The point cloud generation doesnt have good quality at common region. They have verical difference is elevation data of same area. So I though of using cmvs, this might solve that problem. Do you have any suggestion?

**Comment by pmoulon** [comment]
If you are just running CMVS you can certainly tweak the code in order to unload the image data pointer and so be able to still process your dataset.
