### ISSUE TITLE
Different results between elaborations

### ISSUE THREAD

**Issue by roby23** [pmoulon/CMVS-PMVS#29]
I noticed that running PMVS on the same dataset and with the same parameters, gives different results between elaborations.
The differences are both in the number of points and their position. 
Not big differences but I just want to understand why it's happening. 
I think it has something to do with multi thread, because if I run it with CPU = 1 I get the same result 
every time.
Can you confirm this behaviour? Is there a way to fix it?

Thanks

**Comment by pmoulon** [comment]
Unfortunately multithreading is making some operations in a different order and so will always produce a bit different output.

**Comment by roby23** [comment]
So it's not a problem of race conditions, it's just that the data comes every time in a different order giving slightly different results. Good to know, so I must use it with a single thread to have a consistent result.

Many thanks

**Comment by roby23** [comment]
Just a quick info, is it just a problem of the current implementation, or can it be solved rewriting the algorithm in some way?

**Comment by pmoulon** [comment]
I did not write the software so I can't answer.
