### ISSUE TITLE
cmake error on Ubuntu 16.04 64-bit

### ISSUE THREAD

**Issue by chrarndt** [pmoulon/CMVS-PMVS#31]
I am having trouble compiling the code on Ubuntu 16.04 64-bit. I followed the steps in the Readme.txt and do the following in program/main:
` $ mkdir OutputLinux`
` $ cd OutputLinux `
 `$ cmake . .. `
`$ make `

Make throws the following error:

> [ 16%] Building CXX object CMakeFiles/pmvs2.dir/pmvs2.o
In file included from /media/storage/Downloads/CMVS-PMVS-master/program/main/pmvs2.cc:3:0:
/media/storage/Downloads/CMVS-PMVS-master/program/main/../base/pmvs/findMatch.h:12:25: fatal error: tinycthread.h: No such file or directory
compilation terminated.
CMakeFiles/pmvs2.dir/build.make:62: recipe for target 'CMakeFiles/pmvs2.dir/pmvs2.o' failed
make[2]: *** [CMakeFiles/pmvs2.dir/pmvs2.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pmvs2.dir/all' failed
make[1]: *** [CMakeFiles/pmvs2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Tinythread is in the main/thirdParty directory, but i think it might be searching for it in the wrong directory. I am not very experienced in building code from source, so I don't know how to fix this...
Using the precompiled Linux binaries doesn't work either (probably because it is a 32-bit version). It gives the following error:

> ./pmvs2: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory

even though libjpeg-dev is installed.

It would be awesome if someone could help me getting PMVS to work, so I can use it on the point clouds provided by openMVG :)

**Comment by eboudrand** [comment]
You must compile in program not in program/main. Readme.txt is not accurate.

**Comment by chrarndt** [comment]
Thank you for the help, it worked ;)
But there is still a problem. Even though the program starts properly and does its thing, it freezes my computer completely at some point when it just says "done" at the bottom. 
I will investigate in the next few days...

**Comment by nh2** [comment]
@chrarndt Is this still a problem? CMVS-PMVS works fine for me on Ubuntu 16.04.
