### ISSUE TITLE
CMVS infinite loop

### ISSUE THREAD

**Issue by roby23** [pmoulon/CMVS-PMVS#33]
Hello, 

I'm having some problems with CMVS. Sometimes it gets in an infinite loop. I found some forums where they just say that it is a known bug and the solution is to stop it and use it with a different cluster size.

If it is a known bug, why no one has resolved it yet?

Do you have any plan to resolve it? Or any hint to give me for a possible solution?

Many thanks

**Comment by pmoulon** [comment]
I would advise you to use the new OpenMVG clustering algorithm https://github.com/openMVG/openMVG/issues/857#issuecomment-292707035

**Comment by roby23** [comment]
Thanks for the advice, OpenMVG clustering solved the problem

**Comment by pmoulon** [comment]
Can you close the issue?
