### ISSUE TITLE
The result of CMVS only contains camera classification,without point classification

### ISSUE THREAD

**Issue by rock0201** [pmoulon/CMVS-PMVS#40]
Hi! I have ran CMVS, set maximages to 30, a total of 110 pictures，But only output the three files centers-0000.ply, centers-0000.ply, centers-0000.ply,  I want to know how to get the information of pictures and the 3D points which are separated.

**Comment by pmoulon** [comment]
You can look to the pmvs_options.txt files and the camera ID that are kept will be listed there.
CMVS clusters camera taking into account point visibility, but the point clustering is not exported since PMVS does not need it.
