### ISSUE TITLE
CMVS output file.

### ISSUE THREAD

**Issue by 478161648** [pmoulon/CMVS-PMVS#41]
Hi,I ran the colmap and got the sfm result. include sparse point cloud,camera poses and images.
I used the colmap command-line convert it to cmvs format.
then I ran the cmvs.exe the i got center-00001.ply ....      
it just has the camera pose. I don't think the output is right.
I think the cmvs's output should include cluster images and cluster points.am I right?
can someone tell what is right output format of the cmvs ?

**Comment by pmoulon** [comment]
CMVS is computer clusters that can be processed independently by `pmvs2` (Point Cloud computation)
I would advise you to first try to use `pmvs2`, and if it is too slow or memory consuming use CVMS + PMVS
