### ISSUE TITLE
Suggested linux distro - libgfortran.so.3

### ISSUE THREAD

**Issue by canonex** [pmoulon/CMVS-PMVS#43]
I'm trying to run CMVS-PMVS in Debian 10 but linux binaries ( in  OutputLinux32-gcc4.4.1 ) returns an error:
`error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory`

Are they for Linux 32bit as the name suggests?
Debian 10 packages only contain libgfortran from version 4 and it is difficult to rebuild the whole ecosystem to rebuild libgfortran3.

which distribution can I use so that it works smoothly (compiling software is not really my area of expertise)?

Thank you,
Riccardo

**Comment by pmoulon** [comment]
I see two possible choices:
- make a symbolic link named libgfortran.so.3 that point to your libgfortran 4 and see if it is working.
- else use a Ubuntu like distrib.

**Comment by canonex** [comment]
Thank you, a symbolic link works.

**Comment by pmoulon** [comment]
Have fun!
