### ISSUE TITLE
"Filter Exact: Killed"

### ISSUE THREAD

**Issue by pomputer** [pmoulon/CMVS-PMVS#44]
Hi!
Running pmvs2 using VisualSFM produces the error "Filter Exact: Killed". I run ArchLinux. I tried running the command manually and got the same error. I also tried running the same command on the original version of pmvs and got a similar error: "Expanding patches...Killed".

Here is the full output of the command:
`
./pmvs2
/home/patrick/3D-print/photogrammetry/visualsfm/projects/pro/test1.nvm.cmvs/00/
option-0000
--------------------------------------------------
--- Summary of specified options ---
# of timages: 33 (enumeration)
# of oimages: 0 (enumeration)
level: 1  csize: 2
threshold: 0  wsize: 7
minImageNum: 3  CPU: 24
useVisData: 1  sequence: -1
--------------------------------------------------
Reading images: *********************************
8 9 Harris running ...10 Harris running ...Harris running ...11 Harris running ...12 Harris running ...14 15 Harris running ...Harris running ...18 Harris running ...19 Harris running ...21 Harris running ...23 Harris running ...24 Harris running ...25 Harris running ...31 Harris running ...32 Harris running ...33 Harris running ...39 Harris running ...40 Harris running ...41 Harris running ...42 43 Harris running ...45 Harris running ...46 Harris running ...48 Harris running ...Harris running ...16063 harris done
15798 harris done
DoG running...DoG running...15658 harris done
DoG running...15798 harris done
DoG running...16039 harris done
DoG running...15631 harris done
DoG running...15844 harris done
15763 harris done
DoG running...DoG running...16058 harris done
15885 harris done
DoG running...15897 harris done
DoG running...DoG running...15817 harris done
DoG running...15907 harris done
DoG running...15756 harris done
15836 harris done
DoG running...DoG running...15895 harris done
15867 harris done
DoG running...15919 harris done
16149 harris done
16114 harris done
DoG running...DoG running...DoG running...DoG running...15833 harris done
15544 harris done
15756 harris done
DoG running...DoG running...DoG running...15784 harris done
DoG running...20618 dog done
51 Harris running ...20456 dog done
53 Harris running ...20509 dog done
54 Harris running ...20507 dog done
20589 dog done
55 Harris running ...58 Harris running ...20494 dog done
59 Harris running ...20553 dog done
60 Harris running ...20611 dog done
62 Harris running ...20562 dog done
20546 dog done
63 Harris running ...20598 dog done
20524 dog done
20492 dog done
20563 dog done
20583 dog done
20565 dog done
20492 dog done
20412 dog done
20454 dog done
16021 harris done
DoG running...20720 dog done
20240 dog done
20698 dog done
20622 dog done
20703 dog done
16115 harris done
DoG running...15834 harris done
DoG running...16168 harris done
DoG running...16165 harris done
DoG running...15953 harris done
DoG running...16218 harris done
DoG running...16037 harris done
DoG running...15979 harris done
DoG running...20652 dog done
20668 dog done
20643 dog done
20675 dog done
20663 dog done
20446 dog done
20375 dog done
20358 dog done
20558 dog done
done
adding seeds 
(15,3474)(25,10118)(9,9614)(1,9034)(8,0)(6,394)(5,8887)(7,4)(2,11149)(16,34)(17,12781)(18,13370)(0,12756)(19,15870)(10,14716)(12,17751)(11,13936)(26,17164)(21,14114)(20,14050)(24,20257)(23,15689)(3,5469)(4,19050)(14,13340)(27,19494)(28,12884)(29,8588)(31,20089)(13,18257)(30,6876)(32,19428)(22,0)done
---- Initial: 0 secs ----
Total pass fail0 fail1 refinepatch: 1411644 750380 532757 128507 878887
Total pass fail0 fail1 refinepatch: 100 53.1565 37.7402 9.10336 62.2598
Expanding patches...refinePatchBFGS failed!
refinePatchBFGS failed!
refinePatchBFGS failed!
refinePatchBFGS failed!

---- EXPANSION: 262 secs ----
Total pass fail0 fail1 refinepatch: 8550152 8374426 129901 45825 8420251
Total pass fail0 fail1 refinepatch: 100 97.9448 1.51928 0.535955 98.4807
FilterOutside
mainbody: 
Gain (ave/var): 1.02136 3.32614
8752812 -> 4817260 (55.0367%)	0 secs
Filter Exact: Killed`

**Comment by pmoulon** [comment]
Did you try play with the parameters (no visual data, less thread)?
You can change those parameters in the pmvs txt files.

**Comment by pomputer** [comment]
I fixed it by enabling swap, apparently ran out of memory. Now I am encountering another issue. Pmvs2 now gets stuck at "Expanding Patches...":

> --------------------------------------------------
> --- Summary of specified options ---
> # of timages: 37 (enumeration)
> # of oimages: 0 (enumeration)
> level: 1  csize: 2
> threshold: 0  wsize: 7
> minImageNum: 3  CPU: 24
> useVisData: 1  sequence: -1
> --------------------------------------------------
> Reading images: *************************************
> 0 1 Harris running ...Harris running ...2 Harris running ...3 Harris running ...5 Harris running ...6 7 Harris running ...Harris running ...8 Harris running ...9 Harris running ...10 Harris running ...11 Harris running ...12 Harris running ...14 Harris running ...15 Harris running ...16 Harris running ...17 Harris running ...19 Harris running ...20 Harris running ...21 Harris running ...23 Harris running ...24 Harris running ...26 Harris running ...28 Harris running ...29 Harris running ...14300 harris done
> DoG running...14620 harris done
> DoG running...14634 harris done
> DoG running...14508 harris done
> DoG running...14703 harris done
> DoG running...14632 harris done
> DoG running...14758 harris done
> DoG running...14388 harris done
> 14289 harris done
> DoG running...14711 harris done
> 14795 harris done
> DoG running...DoG running...DoG running...13977 harris done
> DoG running...14518 harris done
> 14317 harris done
> 14427 harris done
> 14307 harris done
> DoG running...DoG running...DoG running...DoG running...14485 harris done
> 14429 harris done
> DoG running...DoG running...14027 harris done
> 14692 harris done
> DoG running...14383 harris done
> 14744 harris done
> DoG running...14270 harris done
> DoG running...DoG running...DoG running...14755 harris done
> DoG running...17179 dog done
> 30 Harris running ...17214 dog done
> 32 Harris running ...17314 dog done
> 17397 dog done
> 33 Harris running ...34 Harris running ...17386 dog done
> 35 Harris running ...17218 dog done
> 17282 dog done
> 17327 dog done
> 36 Harris running ...37 Harris running ...38 Harris running ...17318 dog done
> 17319 dog done
> 39 Harris running ...40 Harris running ...17268 dog done
> 41 Harris running ...17379 dog done
> 42 Harris running ...17373 dog done
> 17108 dog done
> 45 Harris running ...17350 dog done
> 17346 dog done
> 17256 dog done
> 17297 dog done
> 17386 dog done
> 17435 dog done
> 17331 dog done
> 17289 dog done
> 17274 dog done
> 17375 dog done
> 12586 harris done
> DoG running...12766 harris done
> DoG running...12626 harris done
> DoG running...12700 harris done
> DoG running...13876 harris done
> DoG running...14654 harris done
> DoG running...12522 harris done
> 14249 harris done
> DoG running...12731 harris done
> DoG running...DoG running...14641 harris done
> DoG running...14007 harris done
> DoG running...12633 harris done
> DoG running...14413 harris done
> DoG running...15455 dog done
> 15290 dog done
> 15479 dog done
> 15500 dog done
> 15434 dog done
> 15507 dog done
> 17258 dog done
> 17452 dog done
> 17381 dog done
> 17463 dog done
> 17444 dog done
> 15460 dog done
> 17417 dog done
> done
> adding seeds 
> (0,9148)(2,13055)(20,352)(23,9293)(4,13665)(5,14823)(1,1)(6,2256)(7,14078)(13,514)(14,4853)(3,0)(18,8626)(15,15170)(9,1979)(8,9898)(19,8781)(11,11332)(21,8296)(31,13071)(32,15966)(17,12400)(16,3475)(12,19493)(10,8257)(29,3611)(30,7588)(27,5357)(26,16211)(25,10690)(28,12130)(24,7624)(35,12476)(36,10510)(22,18068)(33,14114)(34,6944)done
> ---- Initial: 0 secs ----
> Total pass fail0 fail1 refinepatch: 1382905 678382 440452 264071 942453
> Total pass fail0 fail1 refinepatch: 100 49.0549 31.8498 19.0954 68.1502
> Expanding patches...
> ---- EXPANSION: 1355 secs ----
> Total pass fail0 fail1 refinepatch: 9492391 7882153 90403 1519835 9401988
> Total pass fail0 fail1 refinepatch: 100 83.0365 0.952373 16.0111 99.0476
> FilterOutside
> mainbody: 
> Gain (ave/var): -0.245496 2.43858
> 8226017 -> 3753092 (45.6247%)	0 secs
> Filter Exact: *************************************
> 3753092 -> 1892421 (50.423%)	0 secs
> FilterNeighbor:	1892421 -> 1088218 (57.504%)	0 secs
> FilterGroups:	108
> 1088218 -> 238794 (21.9436%)	0 secs
> STATUS: 1663639 0 8680780 0 0 0 0 0 0 0 
> 0 0 0 0 0 0 0 0 0 0 
> 0 0 0 0 0 0 0 0 0 0 
> 0 0 0 0 0 
> Expanding patches...^[[A
> ---- EXPANSION: 1511 secs ----
> Total pass fail0 fail1 refinepatch: 12206666 6129108 156663 5920895 12050003
> Total pass fail0 fail1 refinepatch: 100 50.2112 1.28342 48.5054 98.7166
> FilterOutside
> mainbody: 
> Gain (ave/var): 1.14781 1.94996
> 6367902 -> 5212291 (81.8526%)	0 secs
> Filter Exact: *************************************
> 5212291 -> 2196424 (42.1393%)	0 secs
> FilterNeighbor:	2196424 -> 1762114 (80.2265%)	0 secs
> FilterGroups:	176
> 1762114 -> 717678 (40.7282%)	0 secs
> STATUS: 3320646 0 19073748 0 0 0 0 0 0 0 
> 0 0 0 0 0 0 0 0 0 0 
> 0 0 0 0 0 0 0 0 0 0 
> 0 0 0 0 0 
> Expanding patches...

**Comment by pmoulon** [comment]
Try change level from 1 to 2 in your parameter file and you will be good

**Comment by pomputer** [comment]
That fixed it! Thanks!
