### ISSUE TITLE
cuda-cublas-dev-6-5 - more efficient than default lib?

### ISSUE THREAD

**Issue by pwbecker** [pmoulon/CMVS-PMVS#7]
Thanks for maintaining this!

Nvidia's CUDA system has a library as above, which uses the GPU cores.  Is the default BLAS library as efficient as this, or would it be worth trying to use the CUDA lib, perhaps by using the blaswrap functionality?

Any advice would be much appreciated.

**Comment by pmoulon** [comment]
`blas` is not required anymore by the updated version.
